### ISSUE TITLE
注册用户名限制问题

### ISSUE THREAD

**Issue by AmyF** [lijy91/daza-frontend#1]
为了确认这个bug，进行了第二次注册。两次注册信息只有邮箱区别。
以下为第二次注册过程。
填写完注册信息，点击注册。此时，填写的用户名是4个英文字母。页面提示 用户名字符应大于5，但页面并没有刷新或者跳转等，只有一个提示。
不改变注册信息，再次点击注册按钮。页面提示，邮箱已经注册，用户名已经存在。
点击登录，填写刚才注册的邮箱密码（刚才提示注册失败），结果登录成功。

**Comment by lijy91** [comment]
后端的用户名验证的长度和前端的限制长度不一致导致的问题，现已修正。
