### ISSUE TITLE
文章详情页显示Not Found

### ISSUE THREAD

**Issue by NEtOrnANtHeR** [lijy91/daza-frontend#2]
文章详情页面，无法打开，应该是router层的问题。

在Web端：
https://daza.io/topics/10/articles

在iOS客户端上的文章详情页
![image](https://cloud.githubusercontent.com/assets/11695765/22626579/d01fad5c-ebeb-11e6-94d3-bacdd61011f5.png)

**Comment by lijy91** [comment]
年前提交了一个新域名备案，所以暂时把 daza.io 的内容替换成个人博客了，所以才会出现这个问题
